### ISSUE TITLE
Icon request: Solaar

### ISSUE THREAD

**Issue by user1-github** [L4ki/Magna-Plasma-Themes#3]
Hi, and thanks again for the amazing theme :)

If you accept icon requests, I would love to have an icon for Solaar, the Logitech peripherals manager.

Here is its default icon:

![solaar](https://github.com/L4ki/Magna-Plasma-Themes/assets/56021366/59b1f240-300f-4de6-8d89-37ff01248e08)

**Comment by L4ki** [comment]
Hi user1-github, 

I updated the "Magna Themes" yesterday, so the next update will be in 6 days. The icon is already ready.



![io github pwr_solaar solaar](https://github.com/L4ki/Magna-Plasma-Themes/assets/45247573/11e3de1b-d040-4cd1-852d-f2428fc81b0d)

**Comment by user1-github** [comment]
Looks great, thanks!

I think we can close this now.
