### ISSUE TITLE
Applying doc not found

### ISSUE THREAD

**Issue by ghost** [L4ki/Magna-Plasma-Themes#4]
I have a problem applying the theme on my machine, I'm using Linux Fedora 39, help me.  Add the docs also in Readme

**Comment by L4ki** [comment]
HI ankit,

Can you be a little more specific. What Desktop Environment do you use?

**Comment by ghost** [comment]
My desktop environment is Gnome(latest version)

**Comment by L4ki** [comment]
Hi ankit,

Magna Plasma Themes are intended for Plasma Desktop Environment.

Best regards,

**Comment by ghost** [comment]
Thank you for the clarification.
